151507:
  seed: 36666
  learning_rate: 0.0005
  num_hidden: 64
  num_proj_hidden: 64
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.2
  drop_feature_rate_2: 0.2
  tau: 17.0
  tau_decay: 0.0
  num_epochs: 600
  weight_decay: 0.00001
  num_clusters: 7
  num_gene: 3000
  num_neigh: 5
  num_im_neigh: 2
151508:
  seed: 36666
  learning_rate: 0.0005
  num_hidden: 64
  num_proj_hidden: 64
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.2
  drop_feature_rate_2: 0.2
  tau: 2.0
  tau_decay: 0.0
  num_epochs: 140
  weight_decay: 0.00001
  num_clusters: 7
  num_gene: 3000
  num_neigh: 5
  num_im_neigh: 2

151509:
  seed: 36666
  learning_rate: 0.0005
  num_hidden: 64
  num_proj_hidden: 64
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 1
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.2
  drop_feature_rate_2: 0.2
  tau: 38.0
  tau_decay: 0.0
  num_epochs: 320
  weight_decay: 0.00001
  num_clusters: 7
  num_gene: 3000
  num_neigh: 5
  num_im_neigh: 2

151510:
  seed: 36666
  learning_rate: 0.0005
  num_hidden: 64
  num_proj_hidden: 64
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 1
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.2
  drop_feature_rate_2: 0.2
  tau: 45.0
  tau_decay: 0.0
  num_epochs: 160
  weight_decay: 0.00001
  num_clusters: 7
  num_gene: 3000
  num_neigh: 5
  num_im_neigh: 2

151669:
  seed: 39788
  learning_rate: 0.0005
  num_hidden: 64
  num_proj_hidden: 64
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.1
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.2
  tau: 0.4
  tau_decay: 0.00
  num_epochs: 280
  weight_decay: 0.00001
  num_clusters: 5
  num_gene: 3000
  num_neigh: 3
  num_im_neigh: 2

151670:
  seed: 39788
  learning_rate: 0.0005
  num_hidden: 64
  num_proj_hidden: 64
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.1
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.2
  tau: 0.1
  tau_decay: 0.00
  num_epochs: 260
  weight_decay: 0.00001
  num_clusters: 5
  num_gene: 3000
  num_neigh: 3
  num_im_neigh: 2

151671:
  seed: 39788
  learning_rate: 0.0005
  num_hidden: 64
  num_proj_hidden: 64
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 1
  drop_edge_rate_1: 0.1
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.2
  tau: 44.0
  tau_decay: 0.00
  num_epochs: 440
  weight_decay: 0.00001
  num_clusters: 5
  num_gene: 3000
  num_neigh: 3
  num_im_neigh: 2

151672:
  seed: 39788
  learning_rate: 0.0005
  num_hidden: 64
  num_proj_hidden: 64
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.1
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.2
  tau: 47.0
  tau_decay: 0.00
  num_epochs: 520
  weight_decay: 0.00001
  num_clusters: 5
  num_gene: 3000
  num_neigh: 3
  num_im_neigh: 2

151673:
  seed: 39788
  learning_rate: 0.0005
  num_hidden: 64
  num_proj_hidden: 64
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.1
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.2
  tau: 30.0
  tau_decay: 0.00
  num_epochs: 160
  weight_decay: 0.00001
  num_clusters: 7
  num_gene: 3000
  num_neigh: 5
  num_im_neigh: 2

151674:
  seed: 39788
  learning_rate: 0.0005
  num_hidden: 64
  num_proj_hidden: 64
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.1
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.2
  tau: 20
  tau_decay: 0.00
  num_epochs: 120
  weight_decay: 0.00001
  num_clusters: 7
  num_gene: 3000
  num_neigh: 5
  num_im_neigh: 2

151675:
  seed: 39788
  learning_rate: 0.0005
  num_hidden: 64
  num_proj_hidden: 64
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.1
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.2
  tau: 41.0
  tau_decay: 0.00
  num_epochs: 580
  weight_decay: 0.00001
  num_clusters: 7
  num_gene: 3000
  num_neigh: 3
  num_im_neigh: 2

151676:
  seed: 39788
  learning_rate: 0.0005
  num_hidden: 64
  num_proj_hidden: 64
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 1
  drop_edge_rate_1: 0.1
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.2
  tau: 20
  tau_decay: 0.00
  num_epochs: 120
  weight_decay: 0.00001
  num_clusters: 7
  num_gene: 3000
  num_neigh: 5
  num_im_neigh: 2

Human_Breast_Cancer:
  seed: 39788
  learning_rate: 0.0005
  num_hidden: 64
  num_proj_hidden: 64
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 1
  drop_edge_rate_1: 0.1
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.2
  tau: 8.0
  tau_decay: 0.00
  num_epochs: 520
  weight_decay: 0.00001
  num_clusters: 20
  num_gene: 3000
  num_neigh: 3
  num_im_neigh: 2

Mouse_Brain_Anterior:
  seed: 39788
  learning_rate: 0.0005
  num_hidden: 64
  num_proj_hidden: 64
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 1
  drop_edge_rate_1: 0.1
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.2
  tau: 30.0
  tau_decay: 0.00
  num_epochs: 160
  weight_decay: 0.00001
  num_clusters: 52
  num_gene: 3000
  num_neigh: 3
  num_im_neigh: 2

Mouse_Brain_Posterior:
  seed: 39788
  learning_rate: 0.0005
  num_hidden: 64
  num_proj_hidden: 64
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 1
  drop_edge_rate_1: 0.1
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.2
  tau: 9.0
  tau_decay: 0.00
  num_epochs: 250
  weight_decay: 0.00001
  num_clusters: 20
  num_gene: 3000
  num_neigh: 5
  num_im_neigh: 2

WSA_LngSP8759312:
  seed: 39788
  learning_rate: 0.0005
  num_hidden: 64
  num_proj_hidden: 64
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.1
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.2
  tau: 9.0
  tau_decay: 0.00
  num_epochs: 250
  weight_decay: 0.00001
  num_clusters: 20
  num_gene: 3000
  num_neigh: 4
  num_im_neigh: 2


b0708:
  seed: 36666
  learning_rate: 0.0005
  num_hidden: 64
  num_proj_hidden: 64
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.2
  drop_feature_rate_2: 0.2
  tau: 17.0
  tau_decay: 0.0
  num_epochs: 600
  weight_decay: 0.00001
  num_clusters: 7
  num_gene: 3000
  num_neigh: 5
  num_im_neigh: 2

b0809:
  seed: 36666
  learning_rate: 0.0005
  num_hidden: 64
  num_proj_hidden: 64
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.2
  drop_feature_rate_2: 0.2
  tau: 17.0
  tau_decay: 0.0
  num_epochs: 600
  weight_decay: 0.00001
  num_clusters: 7
  num_gene: 3000
  num_neigh: 5
  num_im_neigh: 2

mouse:
  seed: 36666
  learning_rate: 0.0005
  num_hidden: 64
  num_proj_hidden: 64
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 1
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.2
  drop_feature_rate_2: 0.2
  tau: 17.0
  tau_decay: 0.0
  num_epochs: 600
  weight_decay: 0.00001
  num_clusters: 30
  num_gene: 3000
  num_neigh: 5
  num_im_neigh: 2

bzz:
  seed: 36666
  learning_rate: 0.0005
  num_hidden: 64
  num_proj_hidden: 64
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 1
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.2
  drop_feature_rate_2: 0.2
  tau: 17.0
  tau_decay: 0.0
  num_epochs: 600
  weight_decay: 0.00001
  num_clusters: 10
  num_gene: 3000
  num_neigh: 5
  num_im_neigh: 2